version: "3.5"
services:
    wikidsws:
        container_name: "wikidsws"
        restart: "always"
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
            - '${CERT_PATH}:/app/cert'
            - '/app/node_modules'
        working_dir: /app
        ports:
            - "4000:4000"
