services:
    wikids-ws:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
            - '${CERT_PATH}:/app/cert'
        working_dir: /app
        ports:
            - "4000:4000"
